name: Test Spring
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run Test
        run: |
          echo ${{ env.NAME }}  
          mvn spring-boot:run
          # Clone the project B repository
          git clone https://github.com/LucasBonanno/desafio-api-alelo-lucas-bonanno-casanova.git
          cd project-b
          # Run the tests
          mvn test
        env:
          NAME: ${{ vars.NAME_VARIABLE }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: evidences/report.json
  check-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Display Test Results
        run: |
          # Get the test results
          echo "Test Results: $(cat test-results.json)"

    body: |
      *Test Results:*
      ${{ steps.check-results.outputs.test-results }}

      *Warning:* The tests in project B failed